# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmark_name', models.CharField(max_length=100)),
                ('bookmark_url', models.CharField(max_length=255)),
            ],
        ),
    ]
