# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20180117_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
