# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_product_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
