# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0007_auto_20180118_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='place',
            new_name='product_place',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='search',
            new_name='product_search',
        ),
    ]
