# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_product_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_search',
        ),
        migrations.AddField(
            model_name='product',
            name='search',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
