# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_auto_20180119_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
