# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0011_auto_20180119_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='bookmark_url',
            new_name='User_url',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='bookmark_name',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='product',
            name='search',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
