# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0012_auto_20180119_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_time',
        ),
        migrations.AddField(
            model_name='product',
            name='created_time1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
