# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0014_auto_20180119_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_time1',
            new_name='created_time',
        ),
    ]
