# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0017_product_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='lowshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest', models.CharField(max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
