# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0019_lowshop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowshop',
            name='lowcount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
