# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0024_lowshop_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowshop',
            name='created_at',
        ),
    ]
